version: "3"

services:
  metasploit_container:
    container_name: metasploit_container
    build:
      ./myworking
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./myworking:/myworking
    tty:
      true

